name: EC2 Run Command

on: 
  workflow_dispatch:
    inputs:
      region:
        description: 'Which AWS region to use for the EC2 instance.'
        required: true
        default: 'us-west-2'
        type: choice
        options:
        - 'us-west-2'
      instance:
        description: 'Which AWS EC2 machine type to use.'
        required: true
        default: 'p2.xlarge'
        type: choice
        options:
        - 'p2.xlarge'
        - 'p3.2xlarge'
      storage:
        description: 'How much storage to request with the instance (GB).'
        required: true
        default: '64'
        type: string
      command:
        description: 'The command to run in the CLI with the full kwargs.'
        required: true
        type: string

jobs:
  build-and-push-images:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3

      - name: Log in to the Container Registry
        uses: docker/login-action@465a07811f14bebb1938fbed4728c6a1ff8901fc
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@c4ee3adeed93b1fa6a762f209fb01608c1a22f1e
        with:
          images: ghcr.io/${{ github.repository }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@c56af957549030174b10d6867f20e78cfd7debc5
        with:
          context: docker
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Take a Nap
        run: sleep 15s

  deploy-runner:
    needs: build-and-push-images
    runs-on: ubuntu-latest
    steps:
      - uses: iterative/setup-cml@v1
      - uses: actions/checkout@v3
      - name: Deploy Runner on EC2
        env:
          REPO_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          cml runner \
              --cloud=aws \
              --cloud-region=${{ github.event.inputs.region }} \
              --cloud-type=${{ github.event.inputs.instance }} \
              --cloud-hdd-size=${{ github.event.inputs.storage }} \
              --labels=cml-runner

  run-command:
    needs: deploy-runner
    runs-on: [self-hosted, cml-runner]
    timeout-minutes: 4320 # 72h
    container:
      # hardcoded repo name because docker image pull is bad and can't handle capital letters
      image: docker://ghcr.io/pugetsoundclinic-pit/speakerbox-analysis:main
      options: --gpus all
    steps:
      - uses: actions/checkout@v3
      - name: Run Command
        env:
          REPO_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          ${{ github.event.inputs.command }}
